language: generic 
sudo: requires
services: 
  - docker


before_install:
  - docker build -t misterwhy/docks-and-kubes-course -f Dockerfile.dev .

script:
  - docker run -e CI=true misterwhy/docks-and-kubes-course npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-us-west-2-804057691243"
  bucket-path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY